all: compile link

compile: 
	g++ -std=c++17 -c main.cpp text_field.cpp button.cpp control_element.cpp gui.cpp -I"C:\Users\Administrator\Documents\libraries\SFML-2.5.1 32-bit\SFML-2.5.1\include"


link:
	g++	-std=c++17 main.o text_field.o control_element.o button.o gui.o -o build/main -L"C:\Users\Administrator\Documents\libraries\SFML-2.5.1 32-bit\SFML-2.5.1\lib" -lsfml-graphics -lsfml-window -lsfml-system
